import React, { useState } from "react";
import { useApp } from "../../context/AppContext";
import {
  X,
  Bookmark,
  Trash2,
  ExternalLink,
  Download,
  Calendar,
  CheckCircle2,
  Search,
} from "lucide-react";

export const SavedReportsModal: React.FC = () => {
  const {
    savedReportsModalOpen,
    setSavedReportsModalOpen,
    savedReports,
    deleteReport,
    selectToolById,
  } = useApp();

  const [search, setSearch] = useState("");

  if (!savedReportsModalOpen) return null;

  const filteredReports = savedReports.filter(
    (r) =>
      r.toolName.toLowerCase().includes(search.toLowerCase()) ||
      r.summary.toLowerCase().includes(search.toLowerCase()) ||
      r.inputSnippet?.toLowerCase().includes(search.toLowerCase())
  );

  const handleDownload = (report: (typeof savedReports)[0]) => {
    const text = `SmallSEOTools Saved Report\nTool: ${report.toolName}\nDate: ${report.date}\nScore: ${report.score || "N/A"}\nSummary: ${report.summary}\nInput: ${report.inputSnippet || "N/A"}\n\nGenerated by SmallSEOTools Suite.`;
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${report.toolId}_report_${report.id}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xl max-w-3xl w-full overflow-hidden relative max-h-[85vh] flex flex-col animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="p-6 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-100 text-emerald-700 flex items-center justify-center">
              <Bookmark className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900">Saved Reports & Scan History</h2>
              <p className="text-xs text-slate-500">
                You have {savedReports.length} audits stored securely in your account.
              </p>
            </div>
          </div>

          <button
            onClick={() => setSavedReportsModalOpen(false)}
            className="p-2 text-slate-400 hover:text-slate-600 rounded-full hover:bg-slate-200/60 cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Filter bar */}
        <div className="p-4 border-b border-slate-100 bg-white">
          <div className="relative">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-2.5" />
            <input
              type="text"
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by tool name, snippet, or score..."
              className="w-full pl-9 pr-4 py-2 text-xs bg-slate-50 border border-slate-200 rounded-xl outline-hidden focus:border-emerald-500"
            />
          </div>
        </div>

        {/* Reports List */}
        <div className="p-6 overflow-y-auto space-y-3 flex-1">
          {filteredReports.length === 0 ? (
            <div className="text-center py-12 text-slate-500 text-xs">
              No saved reports found. Run a plagiarism check, SEO score audit, or grammar check and click "Save Report".
            </div>
          ) : (
            filteredReports.map((report) => (
              <div
                key={report.id}
                className="p-4 rounded-xl border border-slate-200 hover:border-emerald-300 bg-slate-50/50 hover:bg-white transition-all space-y-2 group"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-sm text-slate-900">{report.toolName}</span>
                    {report.score && (
                      <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 text-emerald-800">
                        {report.score}
                      </span>
                    )}
                  </div>

                  <div className="flex items-center gap-2 text-slate-400">
                    <span className="text-[11px] flex items-center gap-1">
                      <Calendar className="w-3 h-3" />
                      {report.date}
                    </span>

                    <button
                      onClick={() => handleDownload(report)}
                      className="p-1.5 hover:text-emerald-600 rounded cursor-pointer transition-colors"
                      title="Download Report"
                    >
                      <Download className="w-3.5 h-3.5" />
                    </button>

                    <button
                      onClick={() => deleteReport(report.id)}
                      className="p-1.5 hover:text-rose-600 rounded cursor-pointer transition-colors"
                      title="Delete Report"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </div>

                <p className="text-xs text-slate-600 leading-relaxed font-medium">{report.summary}</p>

                {report.inputSnippet && (
                  <p className="text-[11px] text-slate-400 italic line-clamp-1">
                    "{report.inputSnippet}"
                  </p>
                )}

                <div className="pt-2 flex justify-end">
                  <button
                    onClick={() => {
                      setSavedReportsModalOpen(false);
                      selectToolById(report.toolId);
                    }}
                    className="text-xs text-emerald-600 hover:text-emerald-700 font-bold flex items-center gap-1 cursor-pointer"
                  >
                    <span>Launch in {report.toolName}</span>
                    <ExternalLink className="w-3 h-3" />
                  </button>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </div>
  );
};
