import React from "react";
import { useApp } from "../../context/AppContext";
import {
  X,
  User as UserIcon,
  Crown,
  Shield,
  Clock,
  Sparkles,
  Bookmark,
  LogOut,
  ChevronRight,
  Download,
  Flame,
  ArrowUpRight,
  Layers,
  KeyRound,
} from "lucide-react";
import { downloadTextFile } from "../../utils/downloadHelper";

export const UserDashboardModal: React.FC = () => {
  const {
    userDashboardOpen,
    setUserDashboardOpen,
    user,
    scansRemaining,
    savedReports,
    setPricingModalOpen,
    setAuthModalOpen,
    setSavedReportsModalOpen,
    logoutUser,
    setAdminPanelOpen,
    loginUser,
  } = useApp();

  if (!userDashboardOpen) return null;

  const isPro = user.role === "pro" || user.plan.includes("Pro");
  const isAdmin = user.role === "admin";
  const isGuest = !!user.isGuest;

  const percentUsed = isPro || isAdmin
    ? 100
    : Math.min(100, Math.round((user.dailyScansUsed / (user.dailyLimit || 1)) * 100));

  const handleQuickDownload = (report: (typeof savedReports)[0]) => {
    const text = `SmallSEOTools Saved Report\nTool: ${report.toolName}\nDate: ${report.date}\nScore: ${report.score || "N/A"}\nSummary: ${report.summary}\nInput: ${report.inputSnippet || "N/A"}\n\nGenerated by SmallSEOTools Suite.`;
    downloadTextFile(`${report.toolId}_report_${report.id}.txt`, text);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl border border-slate-200 shadow-2xl max-w-xl w-full overflow-hidden relative max-h-[90vh] flex flex-col animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="px-6 py-5 bg-[#1E293B] text-white flex items-center justify-between border-b border-slate-800">
          <div className="flex items-center gap-3">
            <div className="relative">
              {user.avatar ? (
                <img
                  src={user.avatar}
                  alt={user.name}
                  className="w-12 h-12 rounded-2xl object-cover border-2 border-emerald-400 shadow-sm"
                />
              ) : (
                <div className="w-12 h-12 rounded-2xl bg-slate-700 flex items-center justify-center text-white font-bold text-lg">
                  {user.name.charAt(0)}
                </div>
              )}
              {isPro && (
                <div className="absolute -bottom-1 -right-1 bg-amber-500 text-white rounded-full p-0.5 border border-[#1E293B]">
                  <Crown className="w-3 h-3" />
                </div>
              )}
              {isAdmin && (
                <div className="absolute -bottom-1 -right-1 bg-purple-500 text-white rounded-full p-0.5 border border-[#1E293B]">
                  <Shield className="w-3 h-3" />
                </div>
              )}
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-base font-bold text-white leading-tight">{user.name}</h2>
                <span
                  className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wider ${
                    isAdmin
                      ? "bg-purple-500/20 text-purple-300 border border-purple-500/40"
                      : isPro
                      ? "bg-amber-500/20 text-amber-300 border border-amber-500/40"
                      : isGuest
                      ? "bg-slate-700 text-slate-300 border border-slate-600"
                      : "bg-emerald-500/20 text-emerald-300 border border-emerald-500/40"
                  }`}
                >
                  {user.plan}
                </span>
              </div>
              <p className="text-xs text-slate-400 mt-0.5">{user.email}</p>
            </div>
          </div>

          <button
            onClick={() => setUserDashboardOpen(false)}
            className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-6 overflow-y-auto flex-1">
          {/* Daily Quota Card */}
          <div className="bg-slate-50 border border-slate-200 rounded-2xl p-4 sm:p-5">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <Flame className="w-4 h-4 text-amber-500" />
                <span className="text-xs font-bold text-slate-800 uppercase tracking-wider">
                  Daily Scan & Tool Quota
                </span>
              </div>
              <span className="text-xs font-bold text-slate-600">
                {isPro || isAdmin ? (
                  <span className="text-amber-600 flex items-center gap-1 font-extrabold">
                    <Sparkles className="w-3.5 h-3.5" /> Unlimited Scans
                  </span>
                ) : (
                  <span>
                    <strong className="text-slate-900">{user.dailyScansUsed}</strong> / {user.dailyLimit} scans used
                  </span>
                )}
              </span>
            </div>

            {/* Progress Bar */}
            {!isPro && !isAdmin && (
              <div className="space-y-1.5 mt-3">
                <div className="w-full bg-slate-200 rounded-full h-2.5 overflow-hidden">
                  <div
                    className={`h-full rounded-full transition-all duration-300 ${
                      percentUsed >= 100
                        ? "bg-rose-500"
                        : percentUsed >= 70
                        ? "bg-amber-500"
                        : "bg-emerald-500"
                    }`}
                    style={{ width: `${Math.min(100, percentUsed)}%` }}
                  ></div>
                </div>
                <div className="flex justify-between items-center text-[11px] text-slate-500">
                  <span>
                    {scansRemaining > 0
                      ? `${scansRemaining} scans remaining today`
                      : "Daily limit reached for today"}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-3 h-3 text-slate-400" /> Resets at 00:00 UTC
                  </span>
                </div>
              </div>
            )}

            {/* Guest Banner */}
            {isGuest && (
              <div className="mt-4 p-3 bg-amber-50 border border-amber-200 rounded-xl flex items-center justify-between gap-3">
                <div className="text-xs text-amber-900">
                  <span className="font-bold">You are using a Guest Account.</span>
                  <p className="text-[11px] text-amber-700 mt-0.5">
                    Create a free account to unlock 15 daily scans + saved report history!
                  </p>
                </div>
                <button
                  onClick={() => {
                    setUserDashboardOpen(false);
                    setAuthModalOpen(true);
                  }}
                  className="px-3 py-1.5 bg-amber-600 hover:bg-amber-700 text-white font-bold text-xs rounded-lg whitespace-nowrap cursor-pointer transition-colors shadow-xs"
                >
                  Sign Up Free
                </button>
              </div>
            )}
          </div>

          {/* Quick Metrics */}
          <div className="grid grid-cols-3 gap-3 text-center">
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
              <div className="text-base font-extrabold text-slate-900">{user.reportsGenerated}</div>
              <div className="text-[10px] text-slate-500 uppercase font-semibold mt-0.5">Total Audits</div>
            </div>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
              <div className="text-base font-extrabold text-emerald-600">{savedReports.length}</div>
              <div className="text-[10px] text-slate-500 uppercase font-semibold mt-0.5">Saved Cloud</div>
            </div>
            <div className="p-3 bg-slate-50 border border-slate-200 rounded-xl">
              <div className="text-base font-extrabold text-[#2a69af]">{user.joinedDate || "Today"}</div>
              <div className="text-[10px] text-slate-500 uppercase font-semibold mt-0.5">Member Since</div>
            </div>
          </div>

          {/* Saved Reports Preview */}
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold text-slate-800 uppercase tracking-wider flex items-center gap-1.5">
                <Bookmark className="w-3.5 h-3.5 text-emerald-600" />
                Recent Saved Reports ({savedReports.length})
              </h3>
              {savedReports.length > 0 && (
                <button
                  onClick={() => {
                    setUserDashboardOpen(false);
                    setSavedReportsModalOpen(true);
                  }}
                  className="text-xs text-[#2a69af] hover:underline font-semibold cursor-pointer"
                >
                  View All →
                </button>
              )}
            </div>

            {savedReports.length === 0 ? (
              <div className="p-4 text-center border border-dashed border-slate-200 rounded-xl text-xs text-slate-500">
                No saved reports yet. Run any tool audit and click "Save Report".
              </div>
            ) : (
              <div className="space-y-2">
                {savedReports.slice(0, 3).map((r) => (
                  <div
                    key={r.id}
                    className="p-3 bg-white hover:bg-slate-50 border border-slate-200 rounded-xl flex items-center justify-between gap-3 text-xs transition-colors"
                  >
                    <div className="min-w-0 flex-1">
                      <div className="font-semibold text-slate-800 truncate">{r.toolName}</div>
                      <div className="text-[10px] text-slate-400 mt-0.5">{r.date} • {r.score || "Ready"}</div>
                    </div>
                    <button
                      onClick={() => handleQuickDownload(r)}
                      title="Download report file"
                      className="p-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-lg cursor-pointer transition-colors"
                    >
                      <Download className="w-3.5 h-3.5" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Quick Demo Switcher for Evaluation */}
          <div className="border-t border-slate-100 pt-4">
            <div className="text-[11px] font-semibold text-slate-500 uppercase tracking-wider mb-2">
              Role Testing & Switcher
            </div>
            <div className="grid grid-cols-3 gap-2">
              <button
                onClick={() =>
                  loginUser({
                    id: "usr_guest_001",
                    name: "Guest Visitor",
                    email: "guest@smallseotools.com",
                    role: "user",
                    plan: "Free",
                    isGuest: true,
                    dailyLimit: 3,
                  })
                }
                className={`py-1.5 px-2 text-xs font-semibold rounded-lg border text-center cursor-pointer transition-colors ${
                  isGuest ? "bg-slate-800 text-white border-slate-800" : "bg-slate-50 text-slate-700 border-slate-200 hover:bg-slate-100"
                }`}
              >
                Guest (3 Limit)
              </button>
              <button
                onClick={() =>
                  loginUser({
                    id: "usr_mem_102",
                    name: "Alex Rivera",
                    email: "alex@example.com",
                    role: "user",
                    plan: "Free",
                    isGuest: false,
                    dailyLimit: 15,
                  })
                }
                className={`py-1.5 px-2 text-xs font-semibold rounded-lg border text-center cursor-pointer transition-colors ${
                  !isGuest && !isPro && !isAdmin
                    ? "bg-emerald-600 text-white border-emerald-600"
                    : "bg-slate-50 text-slate-700 border-slate-200 hover:bg-slate-100"
                }`}
              >
                Member (15 Limit)
              </button>
              <button
                onClick={() =>
                  loginUser({
                    id: "usr_pro_888",
                    name: "Sarah Chen",
                    email: "sarah@smallseotools.com",
                    role: "pro",
                    plan: "Pro Business",
                    isGuest: false,
                    dailyLimit: 9999,
                  })
                }
                className={`py-1.5 px-2 text-xs font-semibold rounded-lg border text-center cursor-pointer transition-colors ${
                  isPro
                    ? "bg-amber-600 text-white border-amber-600"
                    : "bg-slate-50 text-slate-700 border-slate-200 hover:bg-slate-100"
                }`}
              >
                Pro (Unlimited)
              </button>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between gap-3">
          {isAdmin ? (
            <button
              onClick={() => {
                setUserDashboardOpen(false);
                setAdminPanelOpen(true);
              }}
              className="px-3 py-2 bg-purple-600 hover:bg-purple-700 text-white text-xs font-bold rounded-xl flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <KeyRound className="w-3.5 h-3.5" />
              Open Admin Console
            </button>
          ) : !isPro ? (
            <button
              onClick={() => {
                setUserDashboardOpen(false);
                setPricingModalOpen(true);
              }}
              className="px-4 py-2 bg-gradient-to-r from-amber-500 to-amber-600 hover:from-amber-600 hover:to-amber-700 text-white text-xs font-bold rounded-xl flex items-center gap-1.5 cursor-pointer shadow-xs shadow-amber-500/20"
            >
              <Crown className="w-3.5 h-3.5" />
              Upgrade to PRO Unlimited
            </button>
          ) : (
            <span className="text-xs text-amber-700 font-bold flex items-center gap-1">
              <Crown className="w-4 h-4 text-amber-500" /> Active PRO Subscription
            </span>
          )}

          <div className="flex items-center gap-2">
            {!isGuest && (
              <button
                onClick={logoutUser}
                className="px-3 py-2 bg-white hover:bg-slate-100 border border-slate-200 text-slate-700 text-xs font-semibold rounded-xl flex items-center gap-1.5 cursor-pointer transition-colors"
              >
                <LogOut className="w-3.5 h-3.5" />
                Sign Out
              </button>
            )}
            <button
              onClick={() => setUserDashboardOpen(false)}
              className="px-4 py-2 bg-slate-900 hover:bg-slate-800 text-white text-xs font-bold rounded-xl cursor-pointer"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
